version: '3.8'

services:
  telegram-monitor:
    build: .
    container_name: telegram-monitor
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Persist session files
      - ./sessions:/app/sessions
      # Optional: Mount logs directory
      - ./logs:/app/logs
    networks:
      - telegram-net

    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/sessions') else 1)"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  telegram-net:
    driver: bridge
